---
language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.1
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
